### ISSUE TITLE
Uso de callback

### ISSUE THREAD

**Issue by lucianopf** [red-light/serverless-101#1]
Bom dia! =)

Isso não é uma real issue, é só um ponto que eu queria deixar aqui exposto, caso o intuito do repositório seja ensinar ou aprender.

O que antigamente era um padrão e podia ser encontrado em qualquer documentação hoje está cada vez mais apagado e difícil de encontrar, então aqui vai um trecho da própria doc da AWS:

> The earlier Node.js runtime v0.10.42 does not support the callback parameter for your Lambda function that runtime v4.3 supports. When using runtime v0.10.42, you use the following context object methods to properly terminate your Lambda function. The context object supports the done(), succeed(), and fail() methods that you can use to terminate your Lambda function. These methods are also present in runtime v4.3 for backward compatibility. For information about transitioning your code to use runtime v4.3, see Transitioning Lambda Function Code to Node.js Runtime v4.3.

`context.succeed()`

Indicates the Lambda function execution and all callbacks completed successfully. Here's the general syntax:

`context.succeed(Object result)`

Ta... e pq eu to falando disso?!

A algum tempo atrás eu tava ensinando pra uma galera o conceito e a aplicação da framework Serverless e a galera não entendia o pq meu código não tinha callbacks, daí eu tive que mostrar pra eles que na verdade, como existe a backward compatibility não era possível criar as funções com callbacks, daí eles mantiveram isso e muito provavelmente irão manter dessa forma.

Eu, como não sou nada fã de callbacks, acredito que é muito mais intuitivo de se ler e se escrever `context.succeed(responseObj)` ou `context.fail(responseObj)`.

Reduz um parâmetro, deixa o código mais semântico e reduz o atrito de usuários lendo o código sem conhecer o comportamento de funções lambda.

Deixo claro que isso é uma opinião e que o objetivo desse comentário é só pra esclarecer que existem outras formas de invocar a resposta dessas funções.

Espero ter ajudado e qualquer coisa estamos aí! =D

**Comment by grvcoelho** [comment]
oi @lucianopf, tudo bem :D Que massa esta issue, valeu!

eu criei este repo para fazer alguns experimentos e juntar um aprendizado sobre serverless/aws em geral.

pelo que eu entendi dos teus comentários e da documentação, além das questões de estilo, não tem diferença eu usar `context.succeed(response)` ou `callback(null, response)`, certo?

:smile:

**Comment by lucianopf** [comment]
Exatamente! rsrs
cb(errorOb, null) = context.fail(errorObj)
cb(null, responseObj) = context.succeed(responseObj)
:smile:

**Comment by grvcoelho** [comment]
Animal! Valeu @lucianopf!
